### PR TITLE
added class to li tag for styling

### PR DESCRIPTION
**Pull request by k-sakoda**
I want to set a left indent at `li`.
like this.
screenshot
But some people are not so.
I fixed for this time so that it can be solved with style sheets.

### CODE REVIEW

**Comment by fzankl** [comment]
@k-sakoda
Am I right with the assumption that you want the map the headings to a tree structure?

**Comment by k-sakoda** [comment]
> @k-sakoda
> Am I right with the assumption that you want the map the headings to a tree structure?

Yes, you are right.

**Comment by hitzhangjie** [comment]
@k-sakoda Hey, guys. I think your method is cleaner than my PR.
Is there something not OK? Looks like the CSS h1,h2,h3... not submitted?

**Comment by fzankl** [comment]
I've implemented this functionality with PR #14 
If this does not fit your needs please feel free to create a new issue.

**Pull request closed without merging**
